FROM ubuntu:18.04

ARG JAVA_VERSION=8
ARG JAVA_UPDATE=201
ARG JAVA_BUILD=09
ARG JAVA_PACKAGE=jdk
ARG JAVA_HASH=42970487e3af4f5aa5bca3f542482c60

ENV LANG C.UTF-8
ENV JAVA_HOME=/opt/jdk
ENV PATH=${PATH}:${JAVA_HOME}/bin

RUN set -ex \
 && apt-get update \
 && apt-get -y install cmake libseccomp-dev gcc g++ \
 && apt-get -y install python python3 python3-pip && pip3 install setuptools --upgrade \
 && apt-get -y install ca-certificates wget unzip \
 && wget -q --header "Cookie: oraclelicense=accept-securebackup-cookie" \
         -O /tmp/java.tar.gz \
         http://download.oracle.com/otn-pub/java/jdk/${JAVA_VERSION}u${JAVA_UPDATE}-b${JAVA_BUILD}/${JAVA_HASH}/${JAVA_PACKAGE}-${JAVA_VERSION}u${JAVA_UPDATE}-linux-x64.tar.gz \
 && mkdir ${JAVA_HOME} \
 && tar -xzf /tmp/java.tar.gz -C ${JAVA_HOME} --strip-components=1 \
 && rm -rf /var/lib/apt/lists/* \
       /tmp/* \
       /root/.wget-hsts

WORKDIR /src